apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: python-app-cert
  namespace: web-app
spec:
  secretName: python-app-tls
  dnsNames:
    - app.yuval-raveh.net
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer