apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deployment.name }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.deployment.label }}
  template:
    metadata:
      labels:
        app: {{ .Values.deployment.label }}
    spec:
      imagePullSecrets:
        - name: {{ .Values.secret.name }}
      containers:
        - name: web-application-container
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: {{ .Values.service.port }}
          startupProbe:
            httpGet:
              port: {{ .Values.service.port }}
              path: /health
          livenessProbe:
            httpGet:
              port: {{ .Values.service.port }}
              path: /health
          readinessProbe:
            httpGet:
              port: {{ .Values.service.port }}
              path: /health
