apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: {{ .Values.deployment.label }}
  type: {{ .Values.service.type }}
  ports:
    - targetPort: {{ .Values.service.port }}
      port: {{ .Values.service.port }}
      protocol: {{ .Values.service.protocol }}