apiVersion: v1
kind: Service
metadata:
  name: web-app-service
  namespace: web-app
spec:
  selector:
    app: web
  type: NodePort
  ports:
    - targetPort: 5000
      port: 5000
      nodePort: 30005
      protocol: TCP